# Generated by Django 2.2.16 on 2022-10-15 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Контакт', 'verbose_name_plural': 'Контакты'},
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(help_text='Укажите действующий адрес электронной почты,', max_length=254),
        ),
    ]
